### ISSUE TITLE
Erro ao criar URL

### ISSUE THREAD

**Issue by lbrsilva-allin** [giep-br/AlUrlShortener-Client#1]
Ao tentar encurtar a URL está retornando erro 500. Segue log:

Server error: `POST http://allbr.co/url/create` resulted in a `500 Internal Server Error` response:\n<html><head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'><title>Slim Application Error</title><sty (truncated...)\n

**Comment by roger-russel** [comment]
Estava sem conexão com o banco, acionei o wando, e ele já corrigiu.
